output "db_endpoint" {
  value       = aws_db_instance.mna.address
  description = "RDS DNS endpoint (public when publicly_accessible is true)"
}

output "db_publicly_accessible" {
  value       = aws_db_instance.mna.publicly_accessible
  description = "Whether the instance has a public DNS name and public IP"
}

output "rds_tls_ca_bundle_url" {
  value       = local.rds_global_tls_ca_bundle_url
  description = "Download this URL to obtain global-bundle.pem for TLS verification (not generated by Terraform)"
}

output "db_port" {
  value = aws_db_instance.mna.port
}

output "db_username" {
  value = aws_db_instance.mna.username
}

output "db_identifier" {
  value = aws_db_instance.mna.identifier
}

output "rds_security_group_id" {
  value = aws_security_group.rds.id
}

output "rds_iam_database_authentication_enabled" {
  description = "Whether IAM DB authentication is enabled on the instance"
  value       = aws_db_instance.mna.iam_database_authentication_enabled
}

output "iam_db_auth_username" {
  description = "PostgreSQL user for IAM DB auth (token from AWS CLI/SDK goes in the password field)"
  value       = var.iam_db_auth_username
}

output "iam_db_connect_policy_arn" {
  description = "Attach this policy (or use attachments from variables) so principals can call generate-db-auth-token for this DB user"
  value       = local.rds_iam_db_auth_enabled ? aws_iam_policy.rds_iam_db_connect[0].arn : null
}

output "iam_db_auth_bootstrap_sql" {
  description = "Run once as master (e.g. psql) after RDS is up, then grant object privileges as needed"
  value       = <<-EOT
    CREATE USER ${var.iam_db_auth_username};
    GRANT rds_iam TO ${var.iam_db_auth_username};
    GRANT CONNECT ON DATABASE ${var.db_name} TO ${var.iam_db_auth_username};
    GRANT USAGE ON SCHEMA public TO ${var.iam_db_auth_username};
    -- Add table/function grants per least privilege, e.g.:
    -- GRANT SELECT ON ALL TABLES IN SCHEMA public TO ${var.iam_db_auth_username};
  EOT
}

output "generate_db_auth_token_cli" {
  description = "Bash/Git Bash/PowerShell: run this, paste the printed string as DBeaver password (SSL on). Token ~15m. Same command in all shells."
  value       = local.rds_iam_db_auth_enabled ? "aws rds generate-db-auth-token --hostname ${aws_db_instance.mna.address} --port ${aws_db_instance.mna.port} --region ${var.aws_region} --username ${var.iam_db_auth_username}" : "(IAM DB auth disabled)"
}

output "generate_db_auth_token_cli_with_profile_example" {
  description = "Example with named AWS CLI profile (adjust profile name)"
  value       = local.rds_iam_db_auth_enabled ? "aws rds generate-db-auth-token --hostname ${aws_db_instance.mna.address} --port ${aws_db_instance.mna.port} --region ${var.aws_region} --username ${var.iam_db_auth_username} --profile MNA-STAGING" : "(IAM DB auth disabled)"
}

output "vercel_rds_iam_user_name" {
  description = "IAM user for Vercel (set AWS_ACCESS_KEY_ID / AWS_SECRET_ACCESS_KEY from a one-time access key for this user). Null if not created."
  value       = try(aws_iam_user.vercel_rds_iam[0].name, null)
}

output "vercel_rds_iam_user_arn" {
  description = "ARN of the Vercel RDS IAM user (null if not created)"
  value       = try(aws_iam_user.vercel_rds_iam[0].arn, null)
}
